// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dequeue": {
            "post": {
                "description": "Remove e retorna o próximo item de uma fila nomeada.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fila"
                ],
                "summary": "Remove item da fila",
                "parameters": [
                    {
                        "description": "Dados do dequeue",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DequeueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "JSON inválido ou campo 'queue' ausente",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Fila não encontrada ou vazia",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/enqueue": {
            "post": {
                "description": "Adiciona um item a uma fila nomeada. Cria a fila se não existir.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "fila"
                ],
                "summary": "Adiciona item à fila",
                "parameters": [
                    {
                        "description": "Dados do enqueue",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.EnqueueRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "adicionado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "JSON inválido ou campos obrigatórios ausentes",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifica se o serviço está online.",
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.DequeueRequest": {
            "type": "object",
            "properties": {
                "queue": {
                    "type": "string"
                }
            }
        },
        "handlers.EnqueueRequest": {
            "type": "object",
            "properties": {
                "item": {
                    "type": "string"
                },
                "queue": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
